# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3a22bcadad48a7c6fd506d5a7d3c656b8e3880b35128265288706d8a8b20145d92d67d178858e3a590cc6117ca694a7f5adf5cc7b6f53062774af9b3acc96d7

test:
  secret_key_base: c0de6ea6c1b455518e6e1e036f097790cd3d5a8c2e0b7ef3798cead788b3ab15fc0893246578bc983d0901015311ab1b44377685bccc056e484fe2654c485e1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
